### PR TITLE
Minor Bug Fixes and Appveyor build environment setup

### PR DESCRIPTION
**Pull request by marcussacana**
- Fixed extraction under non-windows systems
- Fixed crash in the help CLI message
- Setup to build with Appveyor

### CODE REVIEW

**Comment by Sewer56** [comment]
I'm surprised that out of all the things I've worked on, this would be the project that would get a PR, something I get once in a blue moon. I remember just casually cracking the format the day the game released, hacking up this tool quickly and calling it a day. Haven't really looked back here since. 

I didn't even have any of the fancy tools helpful for reading archives I use these days (e.g. [This custom high performance stream reader that would simplify parsing by reading whole structs at once](https://github.com/Reloaded-Project/Reloaded.Memory/blob/master/Source/Reloaded.Memory/Streams/BufferedStreamReader.cs)).

Not really sure why you added an AppVeyor configuration for CI/CD since there are no built-in tests. ¯\\_(ツ)_/¯, there isn't much benefit from my point of view aside from just knowing if master branch can compile.

I'm currently dealing with exams, though if I do get some spare time, I might maybe polish some things up around here (if I can get motivated). This is one of the very few repositories left on my profile that lacks polish. A readme, library form and maybe a packer would be a good start. Since you added a basic AppVeyor config, I might aswell enable it and put a badge if I get around to it.

Thanks for the PR and have a good new year!

**Comment by marcussacana** [comment]
good new year to you too...
Well, about the appveyor, i'm working in the linux, and I thought it would be a pain to download all sdk to compile just one program, so I opted to use appveyor, so it's more personal than necessary, though, since I bothered to configure why not add to PR ?, I thought ... and here we are.

**Comment by Sewer56** [comment]
Yeah I figured you used Linux/nix based system immediately the moment you swapped the path separators in code.

These days (late 2018 onwards) I tend to run everything through `Path.GetFullPath` in my tools as it tends to sanitise the inputs and I often want to pass a full path to avoid issues down the line anyway.

You wouldn't see ugly backslashes in my code, unless the project is by nature Windows only :P (e.g.[Archive Redirection Windows API/FileSystem Level](https://github.com/Sewer56/AfsFsRedir.ReloadedII))

**Comment by marcussacana** [comment]
Yeah, but this FS project is interesting, I thought in something like this before but never really did it, because usually is very much simple just write a repacker.

**Comment by Sewer56** [comment]
Yeah, I never really planned to have a go at it myself until I saw some requests for this kind of functionality in a Discord server and thought "might as well".

With only a repacker you unfortunately run into some limitations, especially when it comes to mixing multiple mods and mod size. Though given you've considered writing one like that before, you probably already know that :P

**Pull request merged**
